FROM node:18.14.2 as builder
WORKDIR /app
COPY . .
RUN npm install -g npm@9.6.3 && npm install && npm run ng build


FROM nginx:alpine 
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/dist/projeto-a3-app .

ENTRYPOINT ["nginx", "-g", "daemon off;"]